version: 2

jobs:
  - docker:
      image: golang:1.14-buster
    template:
      name: go

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-server-sdk-redis-redigo
    description: documentation
